### PR TITLE
Branch update userprofile

### PR DESCRIPTION
**Pull request by Jamarcus111**

### CODE REVIEW

**Comment by CXIA17** [comment]
Detailed update for user profile

**Comment by ZMinghuiZ** [comment]
Good adjustment to the interface that allows the code to be more flexible!

**Comment by Jamarcus111** [comment]
> Detailed update for user profile

Thanks！I will keep working on that

**Comment by Jamarcus111** [comment]
> Good adjustment to the interface that allows the code to be more flexible!

Thanks，hopefully it could become more OOP style

**Pull request merged**
