### PR TITLE
Branch integrate tac game

### PR DESCRIPTION
**Pull request by StargazerX0**
Integrate tictactoe game into the project

### CODE REVIEW

**Comment by Jamarcus111** [comment]
The fixed version of tac game is really engaging

**Comment by ZMinghuiZ** [comment]
I like the feature that allowing the user to pick `X` or `O`.

**Comment by ZMinghuiZ** [comment]
Perhaps it would be better if can implement a exception the detects if the user choose character other than  `X` or `O`

**Comment by StargazerX0** [comment]
> The fixed version of tac game is really engaging

Thank you

**Comment by StargazerX0** [comment]
> I like the feature that allowing the user to pick `X` or `O`.

Thank you

**Comment by StargazerX0** [comment]
> Perhaps it would be better if can implement a exception the detects if the user choose character other than `X` or `O`

Yeah, I will add exception class to handle the situation

**Comment by CXIA17** [comment]
Good job, maybe try to add some error message.

**Pull request merged**
