### PR TITLE
Implement MCQ games

### PR DESCRIPTION
**Pull request by CXIA17**

### CODE REVIEW

**Comment by Jamarcus111** [comment]
The MCQ quesitons are really interesting and i can code while learning Java OOP related concepts which is a fancinating idea

**Comment by ZMinghuiZ** [comment]
Maybe can also add some exception to handle errors when user is not inputing the correct input.

**Comment by CXIA17** [comment]
> Maybe can also add some exception to handle errors when user is not inputing the correct input.

Good idea, I'll implement this suggestion.

**Comment by CXIA17** [comment]
> The MCQ quesitons are really interesting and i can code while learning Java OOP related concepts which is a fancinating idea

Thanks for the complement

**Pull request merged**
