### PR TITLE
Branch fix ped bugs

### LINKED ISSUE #95: [PE-D][Tester A] Illegal Argument Exception not handled well
-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ThawTunZan/ped#1

### LINKED ISSUE #129: [PE-D][Tester D] limits in rasing salaries of employees
I found there is a limit in rasing employee's salary, so I tried to lower their slaray to 0, since the change of salary is no more than the current salary(which is 0), I can not raise the salary anymore :(

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: classskipper351/ped#3

### LINKED ISSUE #130: [PE-D][Tester C] Program crashes under specific circumstances.
Not sure if this one will be relevant. Boss gave 10% bonus. Didnt manage to test this functionality out. BUT the following happened right after:

Steps to reproduce:
1. Type work to start working
2. Type the whole string (without pressing enter)
3. Press enter after typing the whole string.
4. Redo step 2 because somehow that wasn't registered.
5. Have the timer run out before you can complete the 2nd time.
6. Get nothing because i didnt \n
7. Random event happened.
8. typed 'yes', then press enter, and then press enter. An unhandled exception is thrown and the program crashes.

EDIT: The IllegalArgumentException is also thrown for the other random events if i suppled no response, or responses other than yes/no, and not just the particular situation that happened above.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: annoy-o-mus/ped#11

### LINKED ISSUE #131: [PE-D][Tester D] not clear about employee's salary
when I hire employees I do not  know what is their deafult salary , so I do not know how much I spend to pay them or how much I can raise. I wish I can know how much is the salary

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: classskipper351/ped#4

### LINKED ISSUE #132: [PE-D][Tester C] Unhandled NumberFormatException
This exception happens when I try to hire an absurdly large number of employees. Crashes as a result.
This also happens for the fire, lower and raise commands

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: annoy-o-mus/ped#12

### LINKED ISSUE #133: [PE-D][Tester C] Employee numbers, Revenue per employee and Profit per round does not tally up
I am not sure if this has an effect. but the following happened after this event happened.

On a separate note, The "Profit per round" seems to me to be "Profit per employee" instead. The notion of "profit per round" should, to me, also take into account the number of emplpoyees currently employed by the company. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: annoy-o-mus/ped#13

### LINKED ISSUE #136: [PE-D][Tester D] game crash with hire -1 input
when entering hire -1 , game crashes and exits. 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: classskipper351/ped#5

### LINKED ISSUE #139: [PE-D][Tester C] Missing command in user guide: company
The details regarding the company command to check the company status is not found on the user guide (as per the release version not the github[.]io page)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: annoy-o-mus/ped#16

### LINKED ISSUE #140: [PE-D][Tester C] Unable to fire ALL employees after hiring one
It seems that after hiring at least one employee, you must keep at least one of them. Is it intended that we cannot fire all of them?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: annoy-o-mus/ped#17

### LINKED ISSUE #144: [PE-D][Tester C] Documentation Enhancement Suggestion
Can consider placing a Table of Contents so that the users can navigate to the relevant sections faster. Also, adding a page break may be helpful in the document readability for the PDF.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: annoy-o-mus/ped#21

### PR DESCRIPTION
**Pull request by ZMinghuiZ**

### CODE REVIEW

**Review by Jamarcus111 — COMMENTED** [review]
thanks!

**Comment by Jamarcus111** [comment]
Thanks

**Review by CXIA17 — APPROVED** [review]

**Review by Jamarcus111 — APPROVED** [review]
Thanks!

**Review by StargazerX0 — APPROVED** [review]
This bug fix is really important for our project, well done!

**Pull request merged**
